version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  linpack:
    lang: python3-debian
    handler: ./linpack
    image: ${IMAGE_PREFIX}linpack:latest
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
